const T={
trade:{ink:"#0b2f35",paper:"#eef6f5",soft:"#dcefed",accent:"#0f766e"},
health:{ink:"#25352f",paper:"#f5f7f2",soft:"#e7efe7",accent:"#627d68"},
retail:{ink:"#30261f",paper:"#fbf7f1",soft:"#f1e6d8",accent:"#a15c36"},
hospitality:{ink:"#3a221b",paper:"#fff8f0",soft:"#f4e3d2",accent:"#b85f35"},
service:{ink:"#1f2937",paper:"#f7f8fb",soft:"#e8edf5",accent:"#4f67a8"}};
const e=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const app=document.getElementById('app');
const slug=new URLSearchParams(location.search).get('site');
function gallery(){app.innerHTML=`<div class="wrap gallery-head"><div class="eyebrow">50 source-led redesign concepts</div><h1>Caversham website previews.</h1><p class="lead">Each concept is rebuilt from the business’s existing website or, where no standalone site exists, its public business information.</p></div><div class="wrap grid">${B.map(b=>`<a class="gcard" href="?site=${encodeURIComponent(b.slug)}"><div class="tag">${e(b.type)}</div><h3>${e(b.name)}</h3><p>${e(b.headline)}</p></a>`).join('')}</div>`}
function contactBits(b){let out=[];if(b.phone)out.push(`<a href="tel:${e(b.phone.replace(/\s/g,''))}">${e(b.phone)}</a>`);if(b.email)out.push(`<a href="mailto:${e(b.email)}">${e(b.email)}</a>`);if(b.address)out.push(`<span>${e(b.address)}</span>`);return out.join('<span class="dot">•</span>')}
function page(b){
const t=T[b.group]||T.service;
for(const [k,v] of Object.entries(t))document.documentElement.style.setProperty('--'+k,v);
document.title=b.name+' — source-led redesign concept';
const sourceLabel=b.url?'Built from current website':'Built from public business information';
const ctaHref=b.phone?`tel:${b.phone.replace(/\s/g,'')}`:b.email?`mailto:${b.email}`:'#contact';
app.innerHTML=`<div class="concept"><div class="wrap"><span><strong>Source-led redesign concept</strong> · not the live ${e(b.name)} website</span>${b.url?`<a href="${e(b.url)}" target="_blank" rel="noopener">View current site ↗</a>`:'<span>No standalone website found</span>'}</div></div>
<nav class="nav"><div class="wrap"><div class="brand">${e(b.name)}</div><div class="navlinks"><a href="#services">What they offer</a><a href="#proof">Why choose them</a><a class="btn primary" href="${ctaHref}">${e(b.cta)}</a></div></div></nav>
<header class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">${e(sourceLabel)} · Caversham / Reading</div><h1>${e(b.headline)}</h1><p class="lead">${e(b.sub)}</p><div class="hero-actions"><a class="btn primary" href="${ctaHref}">${e(b.cta)}</a><a class="btn secondary" href="#services">See what they offer ↓</a></div><div class="source-note">Content is paraphrased from the current website/public profile, then reorganised for a clearer one-page experience.</div></div>
<div class="hero-art"><div class="signal">${e((b.signal||'Local').split(',')[0])}</div><div class="signal-label">${e((b.signal||'Local business').includes(',')?b.signal.split(',').slice(1).join(',').trim():b.signal)}</div><div class="hero-mini">${b.proof.map(x=>`<span>✓ ${e(x)}</span>`).join('')}</div></div></div></header>
<div class="proof"><div class="wrap"><div><strong>${e(b.type)}</strong><span>Core offer</span></div><div><strong>${e(b.signal)}</strong><span>Public reputation / business signal</span></div><div><strong>Source-led</strong><span>${b.url?'Current website reviewed':'Public information used'}</span></div><div><strong>One page</strong><span>Designed for quicker decisions</span></div></div></div>
<section id="services"><div class="wrap"><div class="section-head"><div class="eyebrow">Current offer, simplified</div><h2>What customers actually need to see.</h2><p>Instead of generic template copy, these sections come from the business’s real offer and are prioritised around the most useful customer decisions.</p></div><div class="cards">${b.services.map((s,i)=>`<article class="card"><div class="card-num">0${i+1}</div><div><h3>${e(s)}</h3><p>Presented as a clear, scannable service rather than buried inside a long navigation structure.</p></div></article>`).join('')}</div></div></section>
<section id="proof" class="story"><div class="wrap story-grid"><div><div class="eyebrow">Why choose them</div><p class="quote">Put the real reasons to trust the business where people can see them.</p></div><div><p>The redesign keeps the strongest claims from the existing website or public profile, without inventing credentials, prices or services.</p><div class="ticks">${b.proof.map(x=>`<div class="tick"><b>✓</b><div>${e(x)}</div></div>`).join('')}</div></div></div></section>
<section id="contact" class="contact"><div class="wrap contact-box"><div><div class="eyebrow">Contact</div><h2>${e(b.cta)}.</h2><p>Use the business’s real public contact details or continue to the current website.</p><div class="contact-real">${contactBits(b)||'<span>Use the current site or public listing to contact the business.</span>'}</div></div><div class="form faux"><div class="form-kicker">A better conversion block</div><h3>One clear next step.</h3><p>Instead of a generic form, the live version would connect this action to the business’s preferred booking, phone, WhatsApp or enquiry flow.</p><a class="btn primary" href="${ctaHref}">${e(b.cta)}</a>${b.url?`<a class="btn secondary" href="${e(b.url)}" target="_blank" rel="noopener">Open current website</a>`:''}</div></div></section>
<footer><div class="wrap"><span>${e(b.name)} · speculative redesign concept</span><span>${e(sourceLabel)}</span></div></footer><a class="back" href="./">← All 50 previews</a>`}
const b=B.find(x=>x.slug===slug);b?page(b):gallery();